#! /usr/bin/env tclsh

set sourceDirectory [file dirname [file normalize [info script]]]
lappend auto_path [file join $sourceDirectory lib]
package require xvfs

proc ::xvfs::callback::setOutputFileName {file workingDirectory inputFile outputDirectory outputFile} {
	if {$outputFile eq ""} {
		return $outputFile
	}

	set outputFile [expr rand()]

	return $outputFile
}

::xvfs::run --directory [pwd]/example --name random
