#! /usr/bin/env tclsh

set sourceDirectory [file dirname [file normalize [info script]]]
lappend auto_path [file join $sourceDirectory lib]
package require xvfs

proc ::xvfs::callback::setOutputFileName {args} {
	return "/"
}

proc ::xvfs::callback::addOutputFiles {fsName} {
	::xvfs::processFile $fsName "" "" {
		type directory
		children "foo"
	}
	::xvfs::processFile $fsName "" "foo" {
		type file
		fileContents "abc"
	}
	::xvfs::processFile $fsName "./xvfs-create-synthetic" "xvfs-create-synthetic" {
		type file
	}
	return [list "" "foo" "xvfs-create-synthetic"]
}

::xvfs::run --directory [pwd] --name synthetic
